mobility:
  simulation_time: 1200
  simulation_step: 0.1
  insertion_density: 20
  min_distance: 1000
  vehicle_height: 2

ray:
  frequency: 15100000000  # 6G freq: 7.125–8.4GHz (7.8GHz) / 14.8–15.35GHz (15.1GHz)
  diffraction: True
  edge_diffraction: False
  scattering: False
  scat_keep_prob: 0.001
  scat_random_phases: False
  tx_antenna_pattern: 'tr38901'
  tx_antenna_polarization: 'V'
  rx_antenna_pattern: 'dipole'
  rx_antenna_polarization: 'V'
  max_depth: 4
  num_samples: 1e6
  max_rx_positions: 10000
  preprocess_score_thresh: 10
